### ISSUE TITLE
Unexpected result with EukRep test

### ISSUE THREAD

**Issue by mgabriell1** [patrickwest/EukRep#18]
Hi,
I installed EukRep v0.6.7 in a new conda environment as explained here #14.
The program works, but when I run the test script I get the following output:
```
 $ ./EukRep_tests.py

------------------------------------------------------------
Prediction tests to be performed on 13 total sequences
Test sequences located in ~/EukRep_tests/test_sequences/test_scaffolds.fa
------------------------------------------------------------

Running test predictions with 3mers...
Expect the following sequences to be predicted to be eukaryotic:
test_seqeunce_1
test_sequence_2
test_sequence_4
test_sequence_5
test_sequence_6
test_sequence_7
test_sequence_8
test_sequence_9
test_sequence_10
test_sequence_11
test_sequence_12
test_sequence_13
The following sequences were predicted to be eukaryotic:
test_seqeunce_1
test_sequence_2
test_sequence_5
test_sequence_6
test_sequence_9
test_sequence_11
test_sequence_12

Missing scaffold test_sequence_4 in 3mer_out.fa
Traceback (most recent call last):
  File "./EukRep_tests.py", line 89, in <module>
    prediction_test()
  File "./EukRep_tests.py", line 85, in prediction_test
    PredictionTests().run()
  File "./EukRep_tests.py", line 65, in run
    self.unit_test_01(kmer)
  File "./EukRep_tests.py", line 75, in unit_test_01
    'Prediction with kmer length %s returned unexpected result' % kmer_length
AssertionError: Prediction with kmer length 3 returned unexpected result
```
What could be the cause of this "unexpected result"?
Thanks

**Comment by patrickwest** [comment]
Hi,

Thanks for your interest! I haven't been maintaining the test suite and that is the most likely reason. In particular i haven't tested the 3mer model in a while (the one that failed) as the 5mer/6mer models perform much better. 

Did you install by github clone? I don't think the test script is included in the pip/conda install. I will update the test suite asap

**Comment by mgabriell1** [comment]
Hi,
Thank!
I tried to install it in both ways (pip & github clone) on two different environments. 
Then I used the test suite (in case of pip installation I downloaded just that folder from github) to test if everything was working correctly.
